public class ABC_123 {
    public string trainername = 'swathi';
    public string batchname = 'frame';
    public string collegeid = '123456';
    public integer studentnumber = 29;
    public ABC_123( string offlinenumber, integer onli){
        
      system.debug('offlinenumber=='+ offlinenumber);
        system.debug('trainername=='+ trainername);
        trainername='swetha';
        system.debug('trainername=='+ trainername);
        }
    public ABC_123( ){
        trainername ='sitha';
             system.debug('trainername=='+ trainername);
            }

}