public class Accounts {
    public string AccountOwner='Mukul';
    public string AccountSite='w3schools.net';
    public id Parentaccount='0013h00000By5BI';
    public integer Accountnumber=7896523;
    public Integer Annualrevenue=1000000;
    public id Accountworkflow='0013h00000By5BI';
    public date Accountclose;
    public string Accounttype='personal';
    public string Billingstreet='Srinagar';
    public string billingcity='hyd';
    public Accounts(){
        System.debug('Constructor===');
        system.debug('AccountOwner' +AccountOwner);
        string Billingstate='tg';
        string rating='hot';
        Accountnumber=0000001;
        AccountOwner='Mukund';
        AccountSite='colorpick.net';
        Accountclose = system.today();
        
    }
}