public class Contacts {
public string Name='srini';
   public string title='open';
    public string leadsource='web';
    public string mailingaddress='srinagar';
    public string phoneno='1234567890';
    public Contacts (string Name1, integer bcode, boolean adv) {
        string homephone='235689001';
        integer batchcode=001;
        Name= 'srikar';
        Name1= Name;
        system.debug('Name--->'+Name);
        batchcode=bcode;  
        system.debug('batchcode--->'+batchcode);
        bcode= batchcode;
        system.debug('bcode--->'+bcode);
        
        
        
        
    }
    
}