public class If_con1 {
    public Contact con;
    public string contactname = 's';
    public If_con1(){
    con = new Contact(Lastname ='mohan');
        If (con.Lastname == 'Mohan'){
            system.debug('con.name;;;;'+ con);
            
        }else If (con.Lastname == 'sir'){
            system.debug('con.name;;;;'+ con);
            
         }else If (con.Lastname == 'sam'){
            system.debug('con.name;;;;'+ con);
             
          }else If (con.Lastname == 'saha'){
            system.debug('con.name;;;;'+ con);
          }
        If (con.Lastname == 'Mohan'){
            system.debug('con.name;;;;'+ con);
        }
        If (con.Lastname == 'Mohan'){
            system.debug('con.name;;;;'+ con);
        }
       insert con; 

}
}