public class If_con {
    public account acc;
    public string std = 'VLR';
    public If_con(){
        system.debug('std=='+ std);
        if (std== '8th batch'){
            system.debug('std value' +std);
        }else if(std  == 'b') {
            system.debug('std value for else' +std);
        }else if(std  == 'a') {
            system.debug('std value for else' +std);
         } else if(std  == std) {
            system.debug('std value for else' +std);
         }else{
             
         }
    acc= new account();
    }

}