public class Method1 {
public string bankname='td';
    public string address='herndon';
    
    public Method1 (integer salescount, string person1){
     methFirst('sweety',125);   
     string accounttype ='personal';
         system.debug('person1--->'+ person1);
        person1 = 'sweet';
        system.debug('person1---->'+ person1);
           }
    
    public void methFirst(string nam, integer num){
        system.debug('methFirst==');
        string name='swathi';
        name=nam;
        system.debug('name---' + name);
        integer numb =45;
        numb = num; 
        system.debug('numb'+ numb);
        
        
    }
}