public class methodsam3 {
    public string oppowner= 'swathi';
    public boolean isit;
    public methodsam3(integer num1,string name, boolean priv, string spr){
       string accountname ='Marshal';
        string leadsource= 'web';
        methodist('10', num1);
        integer ordernumber = 568978;
        ordernumber=num1;
        system.debug('ordernumber---->'+ ordernumber);
    }
        public methodsam3(){
       string accountname ='Marshal';
        string leadsource= 'web';
           methodist('swat', 20);
             system.debug('oppowner---->'+ oppowner);
        integer ordernumber = 568978;
       
        system.debug('ordernumber---->'+ ordernumber);
    }
    public void methodist(string str, integer inte){
    string st='rani';
        st= str;
        oppowner = str;
        system.debug('oppowner---->'+ oppowner);
        integer intm = 25;
              intm = inte; 
        
    }
}