public class Methodsamp {
    public string batch = 'VLR';
    public integer batchnum =8;
    public Methodsamp (string integ, string st, integer ink){
        mymethods ('onlinevlr', ink, false);
        string batch1= 'Onlyvlr';
        Batch = batch1;
        system.debug('batch---->'+ batch);
            }
    public void mymethods(string ine, integer inl, boolean be){
        mymethods1('janaki');
        string integ = 'online';
         integ = ine;
         integer batchcount = 19;
        batchcount= inl;
        system.debug('batchcount---->'+ batchcount);
        system.debug('integ---->'+ integ);
    } 
    public void mymethods1(string inte){
        string integ = inte; 
        system.debug('integ---->'+ integ);
        
    }       
  

}