public class New2 {
public string doctor='iyer';
    public string address='herndon';
    public string billing='line1';
    public integer officecode=789;
    public boolean review;
    public New2(string doc, integer code, integer batchno, string address1, boolean correct){
        string patientlist='payamount';
        review=false;
        officecode=200;
        string complaintslist='fever';
        officecode= code;
        address= address1;
        correct= review;
        system.debug('doctor--->'+ doctor);
        doctor=doc;
        system.debug('doctor--->'+ doctor);
        system.debug('officecode--->'+ officecode);
         integer batchnumber=999;
        batchnumber=batchno;
        system.debug('batchnumber--->'+ batchnumber);
        doc='swat';
        system.debug('doc--->'+ doc);
                 
     }
}