public class Np_opty {
    public string optname= 'sales1';
    public Opportunity op = new Opportunity();
    public Np_opty(){
    //Opportunity ot = new Opportunity(Name = 'sales2'; AccountId = '0013h00000FddfE'; CurrencyIsoCode = 'USD'; StageName ='Qualification'; CloseDate = system.today());
      //  ot.Name = optname;
       // system.debug('ot...>'+ ot);
      //  insert ot;
        
     
        
    }

}