public class Oct15_wrapper {
    public string str ='rainy';
    public Oct15_wrapper() {
         str = 'heavy rains';
        system.debug('sr===>'+str);
   
    //public void mymeth(){
        
    }
    public class Oct_15_wrapper{
      public string currentstuatuation = 'Watery';
        public Oct_15_wrapper(){
           // str = 'hyderabady water';
        }
        public void mysmlMd(){
            
        }
    }
}