public class opportunity {
public string OpportunuityOwner= 'sitara';
public id AccountName= '0013h00000By5BI';
public string type= 'New Customer';
public Integer OrderNumber=1234;
public integer trackingnumber=7894633;
public integer amount=1000000;
public date Closedate= system.today();
public string stage='Proposal/PricsQuote';
public decimal probability= 75;
public id PrimaryCampignsource='7013h000000cWZN';
public string Deliveryinstallationstatus ='Inprogress';

}