public class Sample2 {
    public string Firstname= 'Swathi';
    public string lastname= 'red';
    public string company= 'b';
    public string title= 'mrs';
    public string Leadsource= 'web';
    public string industry='Banking';
    public date systemdate;
    public date batchstartdate;
    public boolean isit;
    public Sample2() {
    system.debug('Firstname..'+ Firstname);
     system.debug('Lastname..'+ Lastname);
       string account='Personal';
          systemdate= system.today();
          isit= false;
          batchstartdate=system.today();
          firstname='swathi kancherla';
        system.debug('Firstname..'+ Firstname);
          
    } 
   }